import type { Metadata } from "next"
import {
  Geist,
  Geist_Mono,
  Cinzel_Decorative,
  Merriweather,
} from "next/font/google"
import "./globals.css"

// Font configuration for Next.js
const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-cinzel-decorative",
})

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-merriweather",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${merriweather.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
